[package]
name = "rserver"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "rserver"
path = "src/main.rs"

[lib]
name = "rserver"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
